### ISSUE TITLE
This is impresive but...

### ISSUE THREAD

**Issue by BenHerbst** [riidom/riiblog_v2#1]
I do mostly game development and also some side projects on Github ( you starred one thats how I found you and the blog ), and I really love your blog. I can even read it in my main language German. Keep up the great work.
But I don't like to have to click on the hamburger menu to see the blog entries, and on the main page are only the catogories listed but not clickable. I would reverse them so on the main blog site are the blog entries and on the hamburger menu the categories listed. I also use Godot btw

**Comment by riidom** [comment]
Hey, thanks for the feedback!

The front page is indeed a bit of a place holder, originally I wanted to simply display the most recent post there. It somehow proved to be more difficult than expected (probably due to my weird setup), so I kept it like this.

But, this blog will be retired soon anyway, since the whole workflow with updating a SSG is too cumbersome, and I am not really a fan of the whole npm thing.

I am halfway done making a new blog with PicoCMS (PHP-based, flat-file). This means, I just have to push a bunch of new assets accompanying the new post (images mostly), and two .md-files (english and german), and everything else stays untouched. Much simpler, and I hope this will help me to make more posts in future!

When it's live, I will make a message with links on the old blog, and push a final RSS entry under old adress. And update on this issue too.

My first feedback ever haha, really glad to hear that you like the blog :)

**Comment by riidom** [comment]
The new blog is live under https://riidom.eu/posts

RSS: https://riidom.eu/posts/misc/feed

I probably won't make a github repo for it (this one exists mostly because I wanted to show some Svelte stuff in applications).

:tada:

**Comment by BenHerbst** [comment]
Maybe add a comment section and a simple account system like just user name and password no need for email or without account via ip address and nickname? so readers could discuss the things that you write. That would make your Blog more interactive and you would maybe have more fun at writing as you get feedback. Like on dev.to where users also discuss things in the comments

**Comment by riidom** [comment]
Oh yes, I did thinking about comments now and then in past, but somehow forgot about it last days. It adds quite a bit complexity though, or you adopt a 3rd party service (which I don't like to do). But I have read somewhere about just letting people write a mail if they have something to add. Which leads to more well-thought comments on average. I thought, additionally the comments could be added to the bottom of the article manually (shouldn't be too much work, I really don't expect a lot of people to comment honestly:) ).

But I totally forgot about that while working on it, so thanks for the input. Adding that to the todo.

**Comment by BenHerbst** [comment]
Yes, always write every idea down. I recommend org mode in Emacs as it is great for keeping notes, check lists, calendars etc. in just plain text but with a lot of power full features like time tracking etc. Anyway, one thing I really don't like about the Email thing is that the readers can't discuss it under each other. Only you get the email and the other readers don't see it. If you implement a comment system, please also allow sub- comments. And as you don't create a new Github repo for the new project, no one could currently contact you except using this repo...

**Comment by riidom** [comment]
I just made a system where I add the comments to the page, after I receive them in my inbox. This is 100% manual, but I expect it to be very low traffic, so I gonna try it that way for now.

You can see the empty "invite" at bottom of every post, and on https://riidom.eu/posts/001_en I left two test comments.

About the replying, I guess the commenter should start the message with "`Reply to ABC: <message>`". They don't appear nested though and there is no quoting (or any means of formatting) -- as far as the website is concerned, the comments are just a flat list. But I think this is not a problem and people will be able to keep track of it.

All in all a simple implementation, but the blog is pretty simple this time anyway, so it kinda fits, I think :)

Thanks again for reminding me about that!

**Comment by BenHerbst** [comment]
You could also add a simple search feature, just a simple text box under the home, language etc. buttons. And it allows to search for the title, topic, and in also in the articles. Why are there no filters any more?

**Comment by riidom** [comment]
Search is something I may try, there are a few plugins available for PicoCMS, really depends on how good they work, and how well they play with my bi-lingual setup.

For the filters, PicoCMS is PHP-based. When I want some feature, I need to write a plugin in PHP, and I am not very good at that language. The old blog, based on Svelte, was JS-centric, where I can get done a lot more than in PHP.

So to get some special functionality, I basically need to find a plugin that works well with my setup, or I can't have it. I may at some later point dig deeper into PHP, and write my own plugins. But that is something for later/maybe.

I really wanted a blog this time, which won't break regularly because underlying tech updates, and which is simple and quick to update. And I had to make some compromises about functionality for that. Which admittedly hurts a bit, but a blog lives from new posts, so this was the way forward. But this is also why I keep the old one archived and don't feel like deleting it :)
